//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlassPackages
    {
        public int Id { get; set; }
        public string Article { get; set; }
        public string ChamberType { get; set; }
        public int TotalThickness { get; set; }
        public int GlassThickness { get; set; }
    }
}
