//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_orderitem
    {
        public view_orderitem()
        {
            this.view_modelcalc = new HashSet<view_modelcalc>();
        }
    
        public int Idorderitem { get; set; }
        public int IDorder { get; set; }
        public string Name { get; set; }
        public int qu { get; set; }
    
        public virtual ICollection<view_modelcalc> view_modelcalc { get; set; }
        public virtual view_orders view_orders { get; set; }
    }
}
