//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_modelcalc
    {
        public int Idmodelcalc { get; set; }
        public int Idorderitem { get; set; }
        public string Good_marking { get; set; }
        public decimal qustore { get; set; }
    
        public virtual view_orderitem view_orderitem { get; set; }
    }
}
