//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_orders
    {
        public view_orders()
        {
            this.view_orderitem = new HashSet<view_orderitem>();
        }
    
        public int Idorder { get; set; }
        public string name { get; set; }
        public string Seller_name { get; set; }
    
        public virtual ICollection<view_orderitem> view_orderitem { get; set; }
    }
}
